# Generated by Django 4.0.4 on 2022-05-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSimulador', '0002_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProd',
            new_name='nombre',
        ),
    ]
